export const items =[
{
    name:"Nike Air Force 1 Low - Travis Scott" , 
    price:749,
    image:'https://images.stockx.com/360/Nike-Air-Force-1-Low-Travis-Scott-Cactus-Jack/Images/Nike-Air-Force-1-Low-Travis-Scott-Cactus-Jack/Lv2/img01.jpg?auto=compress&w=1140&q=90&dpr=2&updated_at=1606325676&fit=clip&fm=jpg&ixlib=react-9.1.5',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"16",
    category:'nike',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    selectedSize:'',
    count:1
},
{
    name:"Adidas NMD Boost - Hu Pharrell" , 
    price:219,
    image:'https://images.stockx.com/360/adidas-NMD-Hu-Pharrell-Inspiration-Pack-White/Images/adidas-NMD-Hu-Pharrell-Inspiration-Pack-White/Lv2/img01.jpg?auto=compress&w=1140&q=90&dpr=2&updated_at=1607648189&fit=clip&fm=jpg&ixlib=react-9.1.5',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"2",
    category:'adidas',
    selectedSize:'',
    sizes:[
    {
        size:41,
        quantity:0,
        id:1
    },
    {
        size:42,
        quantity:0,
        id:2
    },
    {
        size:44,
        quantity:0,
        id:3
    },
    {
        size:45,
        quantity:0,
        id:4
    },
],
    count:1
},
{
    name:"Nike Air Force 1 Low - Travis Scott White" , 
    price:495,
    image:'https://images.stockx.com/images/Nike-Air-Force-1-Low-Travis-Scott-AF100-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606325807',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"17",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:44.5,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Static" , 
    price:399,
    image:'https://images.stockx.com/images/adidas-Yeezy-Boost-350-V2-Static-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606321247',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"11",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Copper" , 
    price:599,
    image:'https://images.stockx.com/images/Adidas-Yeezy-Boost-350-V2-Core-Black-Copper-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1607648248',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"9",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{   
    name:"Nike Air Force 1 Low - Off White Blue",
    price:79,
    image:'https://images.stockx.com/360/Nike-Air-Force-1-Low-Off-White-MCA-University-Blue/Images/Nike-Air-Force-1-Low-Off-White-MCA-University-Blue/Lv2/img01.jpg?auto=compress&w=1140&q=90&dpr=2&updated_at=1607648502&fit=clip&fm=jpg&ixlib=react-9.1.5',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"1",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:4
        }
    ],
    count:1
},
{
    name:"Adidas NMD Boost - Xr1 Blue" , 
    price:99,
    image:'https://images.stockx.com/images/Adidas-NMD-XR1-Blue-Camo-W.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1612547634',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"4",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43.5,
            quantity:0,
            id:4
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:44.5,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{   name:"Nike Air Vapormax - Black",
    price:165,
    image:'https://images.stockx.com/images/Nike-Air-Vapormax-Flyknit-Black-Dark-Grey.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1611595130',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"5",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41.5,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Adidas NMD Boost - Japan Triple Black" , 
    price:99,
    image:'https://images.stockx.com/images/Adidas-NMD-R1-Japan-Triple-Black-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606324776',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"6",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Nike Ld Waffle " , 
    price:999,
    image:'https://images.stockx.com/images/Nike-LD-Waffle-Sacai-Blue-Multi-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606322509',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"8",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41.5,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44.5,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low - White " , 
    price:70,
    image:'https://images.stockx.com/images/Nike-Air-Force-1-Low-White-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1611163779',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"10",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:6
        },
        {
            size:44.5,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Triple White" , 
    price:249,
    image:'https://images.stockx.com/images/Adidas-Yeezy-Boost-350-V2-Cream-White-1-1.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606322741',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"12",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low - Black Supreme  " , 
    price:89,
    image:'https://images.stockx.com/images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606325289',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"13",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low Off White - Black" , 
    price:890,
    image:'https://images.stockx.com/images/Nike-Air-Force-1-Low-Off-White-Black-White-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606322302',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"14",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{
    name:"Adidas Nite Jogger - Triple Black" , 
    price:79,
    image:'https://images.stockx.com/adidas-Nite-Jogger-Triple-Black-2020.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1603481985',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"15",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Nike Air Uptempo",
    price:120,
    image:'https://images.stockx.com/images/Nike-Air-More-Uptempo-Iridescent-W-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1609431864',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"3",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
        {
            size:46.5,
            quantity:0,
            id:10
        },
    ],
    count:1
},
{
    name:"Nike Air Jordan - Retro " , 
    price:599,
    image:'https://images.stockx.com/images/Air-Jordan-1-Retro-High-85-Varsity-Red-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&dpr=2&trim=color&updated_at=1606322936',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"18",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:6
        },
        {
            size:45,
            quantity:0,
            id:7
        },
        {
            size:46,
                        quantity:0,
            id:9
        },
    ],
    count:1
},
]

