export const items =[
{
    name:"Nike Air Force 1 Low - Travis Scott" , 
    price:749.99,
    image:'/images/nike10.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"16",
    category:'nike',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    selectedSize:'',
    count:1
},
{
    name:"Adidas NMD Boost - Hu Pharrell" , 
    price:219,
    image:'/images/adidas7.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"2",
    category:'adidas',
    selectedSize:'',
    sizes:[
    {
        size:41,
        quantity:0,
        id:1
    },
    {
        size:42,
        quantity:0,
        id:2
    },
    {
        size:44,
        quantity:0,
        id:3
    },
    {
        size:45,
        quantity:0,
        id:4
    },
],
    count:1
},
{
    name:"Nike Air Force 1 Low - Travis Scott White" , 
    price:495,
    image:'/images/nike11.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"17",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:44.5,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Static" , 
    price:399.99,
    image:'/images/adidas3.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"11",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Copper" , 
    price:599,
    image:'/images/adidas4.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"9",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{
    name:"Adidas NMD Boost - Xr1 Blue" , 
    price:99,
    image:'/images/adidas6.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"4",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43.5,
            quantity:0,
            id:4
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:44.5,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{   name:"Nike Air Vapormax - Flyknit",
    price:165,
    image:'/images/nike1.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"5",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41.5,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Adidas NMD Boost - Black" , 
    price:99,
    image:'/images/adidas5.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"6",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Nike Ld Waffle " , 
    price:999,
    image:'/images/nike5.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"8",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41.5,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44.5,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low - White Mens  " , 
    price:70,
    image:'/images/nike7.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"10",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40.5,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:6
        },
        {
            size:44.5,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{
    name:"Adidas Yeezy Boost 350 V2 - Triple White" , 
    price:249.99,
    image:'/images/adidas2.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"12",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low - Red Youth  " , 
    price:89.99,
    image:'/images/nike8.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"13",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
    ],
    count:1
},
{
    name:"Nike Air Force 1 Low Off White - Black" , 
    price:890,
    image:'/images/nike9.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"14",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
    ],
    count:1
},
{
    name:"Adidas Nite Jogger - Triple Black" , 
    price:79,
    image:'/images/adidas1.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"15",
    category:'adidas',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:46,
            quantity:0,
            id:9
        },
    ],
    count:1
},
{   
    name:"Nike Air Force 1 Low - Blue Mens",
    price:79,
    image:'/images/nike4.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"1",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:4
        }
    ],
    count:1
},
{
    name:"Nike Air Uptempo",
    price:120,
    image:'/images/nike3.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"3",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:42.5,
            quantity:0,
            id:4
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:43.5,
            quantity:0,
            id:6
        },
        {
            size:44,
            quantity:0,
            id:7
        },
        {
            size:45,
            quantity:0,
            id:8
        },
        {
            size:46,
            quantity:0,
            id:9
        },
        {
            size:46.5,
            quantity:0,
            id:10
        },
    ],
    count:1
},
{
    name:"Nike Air Jordan - Retro " , 
    price:599,
    image:'/images/nike13.png',
    wishlistImage:'/images/heart-regular.svg',
    description:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut, quos!',
    id:"18",
    category:'nike',
    selectedSize:'',
    sizes:[
        {
            size:40,
            quantity:0,
            id:1
        },
        {
            size:41,
            quantity:0,
            id:2
        },
        {
            size:42,
            quantity:0,
            id:3
        },
        {
            size:43,
            quantity:0,
            id:5
        },
        {
            size:44,
            quantity:0,
            id:6
        },
        {
            size:45,
            quantity:0,
            id:7
        },
        {
            size:46,
                        quantity:0,
            id:9
        },
    ],
    count:1
},
]

